-d D:\Git\gowin\polyphony_minesweeper\impl\gwsynthesis\LEDMatrix.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst D:\Git\gowin\polyphony_minesweeper\src\top.cst
-cfg D:\Git\gowin\polyphony_minesweeper\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
